### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by genkot1** [genkot1/furima-32026#9]
https://furima-32026.herokuapp.com/

basic認証：admin / 2222

よろしくお願い致します。

**Comment by mo1015** [comment]
小髙さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

**※補足　出品者用、購入者用アカウント、カード情報を記載しておきましょう**
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/62644781/102056482-c8e88a00-3e2f-11eb-968d-7dab21543f78.png)
